version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moviesystem
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-mysql-network

#  app:
#    build: .
#    container_name: app-movies
#    restart:
#     always
#    depends_on:
#      - mysql
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/moviesystem
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: root
#    networks:
#      - spring-mysql-network

volumes:
  mysql_data:

networks:
  spring-mysql-network:
    driver: bridge
